version: '3'
volumes:
    influxdb-data:
        driver: local
        driver_opts:
            type: none
            device: ${DATADIR}/influxdb-data
            o: bind
    nodered-data:
        driver: local
        driver_opts:
            type: none
            device: ${DATADIR}/nodered-data
            o: bind    
    grafana-data:
        driver: local
        driver_opts:
            type: none
            device: ${DATADIR}/grafana-data
            o: bind    
    mosquitto-data:
        driver: local
        driver_opts:
            type: none
            device: ${DATADIR}/mosquitto-data
            o: bind    
services:
  nodered:
    restart: always
    build: ./nodered
    volumes:
      - 'nodered-data:/data'
    ports:
      - "1880:1880"
    links:
      - 'influxdb:db'
      - 'mosquitto:mq'
  influxdb:
    restart: always
    build: ./influxdb
    environment:
      - INFLUXDB_DB=ming_default
    volumes:
      - 'influxdb-data:/var/lib/influxdb2'
    ports:
      - "8086:8086"
  grafana:
    restart: always
    build: ./grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    volumes:
      - 'grafana-data:/var/lib/grafana'
    depends_on:
      - influxdb
    links:
      - 'influxdb:db'
  mosquitto:
    restart: always
    build: ./mosquitto
    volumes:
      - 'mosquitto-data:/etc/mosquitto'    
    ports:
      - "1883:1883"
      - "1884:1884"
